[package]
name = "rust_redis_test"
version = "0.1.0"
edition = "2024"

[dependencies]
# redis = "0.32"
redis = { version = "0.32", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"